version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /app/ermp/ermp-actman-web:/app/ermp/ermp-actman-web
      - /app/ermp/ermp-web-new:/app/ermp/ermp-web-new
      - /nas:/nas
      - /app/rayshin-web:/app/rayshin-web
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    restart: always
    network_mode: host
